// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FilterInterface is an autogenerated mock type for the FilterInterface type
type FilterInterface[T interface{}] struct {
	mock.Mock
}

type FilterInterface_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *FilterInterface[T]) EXPECT() *FilterInterface_Expecter[T] {
	return &FilterInterface_Expecter[T]{mock: &_m.Mock}
}

// ShouldProcess provides a mock function with given fields: typeValue
func (_m *FilterInterface[T]) ShouldProcess(typeValue *T) bool {
	ret := _m.Called(typeValue)

	if len(ret) == 0 {
		panic("no return value specified for ShouldProcess")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*T) bool); ok {
		r0 = rf(typeValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FilterInterface_ShouldProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldProcess'
type FilterInterface_ShouldProcess_Call[T interface{}] struct {
	*mock.Call
}

// ShouldProcess is a helper method to define mock.On call
//   - typeValue *T
func (_e *FilterInterface_Expecter[T]) ShouldProcess(typeValue interface{}) *FilterInterface_ShouldProcess_Call[T] {
	return &FilterInterface_ShouldProcess_Call[T]{Call: _e.mock.On("ShouldProcess", typeValue)}
}

func (_c *FilterInterface_ShouldProcess_Call[T]) Run(run func(typeValue *T)) *FilterInterface_ShouldProcess_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *FilterInterface_ShouldProcess_Call[T]) Return(_a0 bool) *FilterInterface_ShouldProcess_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FilterInterface_ShouldProcess_Call[T]) RunAndReturn(run func(*T) bool) *FilterInterface_ShouldProcess_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewFilterInterface creates a new instance of FilterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilterInterface[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *FilterInterface[T] {
	mock := &FilterInterface[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
