// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionsProducer is an autogenerated mock type for the TransactionsProducer type
type TransactionsProducer struct {
	mock.Mock
}

type TransactionsProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionsProducer) EXPECT() *TransactionsProducer_Expecter {
	return &TransactionsProducer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *TransactionsProducer) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionsProducer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type TransactionsProducer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TransactionsProducer_Expecter) Execute(ctx interface{}) *TransactionsProducer_Execute_Call {
	return &TransactionsProducer_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *TransactionsProducer_Execute_Call) Run(run func(ctx context.Context)) *TransactionsProducer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TransactionsProducer_Execute_Call) Return(_a0 error) *TransactionsProducer_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionsProducer_Execute_Call) RunAndReturn(run func(context.Context) error) *TransactionsProducer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionsProducer creates a new instance of TransactionsProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsProducer {
	mock := &TransactionsProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
