name: build_test
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: go build
        run: make build

      - name: go test
        run: make test
