name: ECR
on:
  push:
    tags:
      - 'v*'

jobs:
  ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: allora-producer
          IMAGE_TAG: ${{ github.sha }}
        run: |

          GIT_TAG="$(echo $GITHUB_REF| sed 's#refs/tags/##')"

          docker build -t $REGISTRY/$REPOSITORY:$GIT_TAG -t $REGISTRY/$REPOSITORY:$GIT_TAG .
          docker push $REGISTRY/$REPOSITORY:$GIT_TAG
